### ISSUE TITLE
您好，我在复现代码时遇到了以下错误

### ISSUE THREAD

**Issue by Anlin11** [xufangchn/GLF-CR#5]

**Comment by Anlin11** [comment]
以下是详细信息：
Traceback (most recent call last):
  File "test_CR.py", line 67, in <module>
    main()
  File "test_CR.py", line 64, in main
    test(CR_net, opts)
  File "test_CR.py", line 30, in test
    pred_cloudfree_data = CR_net(cloudy_data, SAR_data)
  File "C:\Users\wang\anaconda3\envs\GLF-CR38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\wang\Desktop\GLF-CR38\codes\net_CR_RDN.py", line 492, in forward
    x, x_SAR = self.fuse(x, x_SAR, i)
  File "C:\Users\wang\Desktop\GLF-CR38\codes\net_CR_RDN.py", line 508, in fuse
    SAR_m = self.DFR[i](SAR_m, kernel_sar)
  File "C:\Users\wang\anaconda3\envs\GLF-CR38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\wang\Desktop\GLF-CR38\codes\FAC\kernelconv2d\KernelConv2D.py", line 87, in forward
    return KernelConv2DFunction.apply(input_pad, kernel, self.kernel_size)
  File "C:\Users\wang\Desktop\GLF-CR38\codes\FAC\kernelconv2d\KernelConv2D.py", line 37, in forward
    kernelconv2d_cuda.forward(input, kernel, intKernelSize, output)
RuntimeError: CUDA call failed
